accumulate_grad_batches: 8
adafactor: false
adam_epsilon: 1.0e-08
attention_dropout: null
cache_dir: ''
config_name: ''
data_dir: /workspace/ceph_data/intermediate/bert-AAE-v2-only-dot-direct-mrpc/6
decoder_layerdrop: null
do_predict: false
do_train: true
encoder_layerdrop: null
eval_batch_size: 32
fp16: false
fp16_opt_level: O2
glue_output_mode: classification
gpus: 1
gradient_clip_val: 1.0
hidden_dropout_prob: 0.25253670535905964
learning_rate: 2.9992055974780028e-05
lr_scheduler: cosine
max_epochs: 3
max_seq_length: 128
model_name_or_path: bert-base-cased
num_workers: 16
output_dir: /workspace/ceph_data/output/bert-AAE-v2-only-dot-direct-mrpc/16
overwrite_cache: false
seed: 2
task: mrpc
tokenizer_name: null
tpu_cores: null
train_batch_size: 2
warmup_steps: 0
weight_decay: 0.0
